kind: pipeline
name: build

platform:
  os: linux

steps:
- name: api
  image: plugins/docker
  settings:
    repo: rkojedzinszky/go-dhcplogger
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
